targets:
  OBAKit:
    type: framework
    platform: iOS
    sources: ["."]
    dependencies:
      - target: OBAKitCore
      - carthage: BLTNBoard
      - carthage: IGListKit
      - carthage: IGListDiffKit
      - package: Connectivity
      - package: Eureka
      - package: FloatingPanel
      - package: MarqueeLabel
      - package: SwipeCellKit
    postBuildScripts:
      - path: "../scripts/swiftlint.sh"
        name: Swiftlint
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: 20.2.0
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: false
