disabled_rules:
  - function_parameter_count
  - identifier_name
  - line_length
  - private_over_fileprivate
  - statement_position
  - todo
  - trailing_comma
  - type_name
  # - colon
  # - comma
  # - control_statement
opt_in_rules: # some rules are only opt-in
  # - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - OBAKit
  - OBAKitCore
  - TodayView
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - OBAKit/SwipeCellKit
  - OBAKitCore/Models/Protobuf/gtfs-realtime.pb.swift
force_try:
  excluded:
    - OBAKitTests
function_body_length:
  excluded:
    - OBAKitTests
file_length:
  warning: 900
  error: 1000
type_body_length:
  warning: 900
  error: 1000
