targets:
  OBAIntents:
    type: app-extension
    platform: iOS
    sources: [
        ".",
        "../Supporting Files"
    ]
    dependencies:
      - target: OBAKitCore
      - sdk: Intents.framework
    entitlements:
      path: Intents.entitlements
    info:
      path: Info.plist
      properties:
        NSExtensionPrincipalClass: IntentHandler
        NSExtension:
          NSExtensionPrincipalClass: OBAIntents.IntentHandler
          NSExtensionPointIdentifier: com.apple.intents-service
          NSExtensionAttributes:
            IntentsRestrictedWhileLocked: []
            IntentsRestrictedWhileProtectedDataUnavailable: []
            IntentsSupported: ["Intent"]
