targets:
  OBAKitCore:
    type: framework
    platform: iOS
    sources: ["."]
    dependencies:
      - package: CocoaLumberjack
      - package: CocoaLumberjackSwift
      - package: SwiftProtobuf
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: 20.2.0
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true
