name: OBAKitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Switch Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.5.app

    - name: Install iOS 14
      run: xcversion simulators --install="iOS 14.5"

    - name: Install xcodegen
      run: brew install xcodegen

    - name: Generate xcodeproj for OneBusAway
      run: scripts/generate_project OneBusAway

    # Build
    - name: Build OneBusAway
      run: xcodebuild clean build-for-testing
        -scheme 'App'
        -destination 'platform=iOS Simulator,OS=14.5.0,name=iPhone 8'
        -quiet

    # Unit Test
    - name: OBAKit Unit Test
      run: xcodebuild test-without-building
        -only-testing:OBAKitTests
        -project 'OBAKit.xcodeproj'
        -scheme 'App'
        -destination 'platform=iOS Simulator,OS=14.5.0,name=iPhone 8'
        -resultBundlePath OBAKitTests.xcresult
        -quiet
    - name: Upload OBAKitTests results
      uses: actions/upload-artifact@v2
      with:
        name: OBAKitTests_xcresult
        path: OBAKitTests.xcresult

    # UI Test
    - name: OBAKit UI Test
      run: xcodebuild test-without-building
        -only-testing:OBAKitUITests
        -project 'OBAKit.xcodeproj'
        -scheme 'App'
        -destination 'platform=iOS Simulator,OS=14.5.0,name=iPhone 8'
        -resultBundlePath OBAKitUITests.xcresult
        -quiet

    # Upload results
    - name: Upload OBAKitUITests results
      uses: actions/upload-artifact@v2
      with:
        name: OBAKitUITests_xcresult
        path: OBAKitUITests.xcresult
